### ISSUE TITLE
Feature request: custom DNS servers

### ISSUE THREAD

**Issue by chazragg** [qdm12/private-internet-access-docker#128]
1. What's the feature?
add the ability to use custom DNS servers.
2. Why do you need this feature?
a lot of the community runs pie hole so manage their local DNS. would be awesome to have support for this
3. Extra information?

**Comment by WoLpH** [comment]
At least for the case of pihole you can already do this easily.

Set these environment variables and you're done:
```
DOT=off
DNS_PLAINTEXT_ADDRESS=<pihole-ip>
```

**Comment by qdm12** [comment]
Thanks @WoLpH  for mentioning that, and sorry @chazragg I forgot to mention it and close the issue. I think I solved a duplicate issue from @Frepke to be able to specify a custom DNS address.

**Comment by timominous** [comment]
@qdm12 Piggybacking on this issue. Are there any possible adverse effects, using the settings above, for having Pihole and Gluetun run on the same machine (same address)?

**Comment by qdm12** [comment]
- If you use your LAN pihole, your DNS requests will go though whatever DNS is configured on Pihole instead of through the VPN
- If you run pihole using the gluetun network stack, then it would be going through the vpn.
- The built-in dns in gluetun uses Unbound with DNS over TLS for encrypted requests, Pihole doesn't do that.

Ideally you could have pihole using the built-in unbound dns over tls, all using the gluetun network stack, but that's quite a bit of development effort to make this work smoothly.

Instead, you could run dns over tls (i. e. using qmcgaw/cloudflare-dns-server) on port 1053 and connected to gluetun, as well as pihole on port 53 connected to gluetun and using `127.0.0.1:1053` as its dns server, and set `DOT=off` and `DNS_PLAINTEXT_ADDRESS=127.0.0.1` in gluetun. That way you would have your DNS requests going through the VPN, through Pihole and encrypted with TLS. A bit of a networking headache but I used a similar setup (without the VPN part).

**Comment by WoLpH** [comment]
Instead of DNS over TLS you do get DNS over HTTP with pihole though

**Comment by qdm12** [comment]
Oh true that, they added that in May I think. So just use a pihole container connected to gluetun on port 53 using dns over https. I will work on bundling pihole in there since it supports dns over https now.

**Comment by qdm12** [comment]
Actually @WoLpH I talked too quickly, it doesn't seem pihole supports dns over https yet right?

**Comment by WoLpH** [comment]
Well... kind of but not natively: https://docs.pi-hole.net/guides/dns-over-https/

**Comment by qdm12** [comment]
Yeah, so you need Unbound for dns over tls (or whatever dns over tls/https you want instead) and make Pihole use that one. On a side note, I'm working on a dns over https Go implementation to replace Unbound/DNS over TLS in this container.

**Comment by sunjam** [comment]
> Oh true that, they added that in May I think. So just use a pihole container connected to gluetun on port 53 using dns over https. I will work on bundling pihole in there since it supports dns over https now.

You could bundle in Adguard Home, which does support dns over https.  https://github.com/AdguardTeam/AdGuardHome
