### ISSUE TITLE
PIA: why use IP instead of hostname in .ovpn?

### ISSUE THREAD

**Issue by Phorze** [qdm12/private-internet-access-docker#129]
Is there a particular reason why? I imagine it also requires maintenance to update all IP's regularly..

**Comment by qdm12** [comment]
The reason is that the firewall is set to only allow communicating with the IP addresses resolved from the hostname at start (although mullvad and windscribe come with fixed IP addresses in their configs), so if the IP changes (only for PIA), it won't work anymore and would be blocked. And now because other vpn service providers give fixed IPs in their config (to avoid relying on DNS resolution before tunneling), it's also better to keep it to IPs whenever possible for consistency :wink:

**Comment by Phorze** [comment]
Thanks.
