### ISSUE TITLE
Error: Unsupported config option for pia service: 'init'

### ISSUE THREAD

**Issue by HerbM3** [qdm12/private-internet-access-docker#158]
I'm a noob and I've tried to figure this out, but cannot. Any ideas why I'm getting this:

> Unsupported config option for pia service: 'init'

**Comment by qdm12** [comment]
It may be because your docker-compose is too old and doesn't support the `init:` option.

What version did you specify at the top for docker-compose.yml (3.7)? What's your docker-compose version (find it with `docker-compose version`)?

If you can't update it (or lazy), I believe you can now remove the `init: true` option as the entrypoint program I wrote ensures all processes exit before exiting the container. This init option is to ensure there is no 'zombie' process leftover when the container shuts down, but it should not be needed anymore I believe.

**Comment by HerbM3** [comment]
Wow. I sure appreciate the quick reply. I am using docker-compose 2.4 through Portainer inside of Open Media Vault. I did get it running, but the status is "Unhealthy"

**Comment by Frepke** [comment]
When using Portainer, the compose version has to be 2 at the max. Portainer isn’t compatible with version 3.

**Comment by qdm12** [comment]
> I am using docker-compose 2.4 through Portainer inside of Open Media Vault.

Yes that's why, it should still work if you remove the init block. The port publishing doesn't affect how the container runs 'inside'. Do you mind sharing your logs when it loop restarts? Thanks and thanks @Frepke for pointing that out :+1:

**Comment by HerbM3** [comment]
Some progress. The restarting I think was caused by using a hyphen instead of a space in the Region. Now it is not restarting, but just shows as healthy, not running.

[log2.txt](https://github.com/qdm12/private-internet-access-docker/files/4624283/log2.txt)

**Comment by HerbM3** [comment]
And I just installed Node Red via Stacks and it says "healthy" as well... I was able to test it out and it's fine. Still learning. I guess I can turn off the HEALTHCHECK...? Still learning. Sorry.

**Comment by qdm12** [comment]
What do you mean by `not running`? I think it's running from the logs you sent. Feel free to close the issue if it works, and recreate an issue if you have any other question or problem :wink:

**Comment by qdm12** [comment]
Nice! Your easiest route would be using `network: "container:pia"` using portainer I think.

Note you can also use the Shadowsocks built-in server which works nice with computers on your LAN (see the readme for how-to). The healthcheck is a Docker built-in thing, maybe you can disable it within your Docker daemon. In this container it just tries to resolve and access github.com periodically to check internet access still works.
