### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by Frepke** [qdm12/private-internet-access-docker#24]
I'm running this container on my arm device for a while now (2 containers for different purposes).
Containers running okay.

I check the health-state and IP-addresses from the containers a few times a day with a cronjob.
The health-state toggles between unhealthy and healthy over the day while the IP-addresses are still the same. 

kr.,
Frepke

**Comment by qdm12** [comment]
Hi there,

Thanks for your input! 

The healthcheck performs the command `ping -W 1 -w 1 -q -s 8 1.1.1.1` where it simply pings Cloudflare's 1.1.1.1 address. So that's just a connectivity test. 

Maybe Cloudflare took too long to respond.

I'm opened to other domain names or IP addressese to ping against, but they would have to work everywhere (i. e. in China as well).

I had a healthcheck back then which would check your IP address but it would fail quite often for a reason I don't exactly recall :smile:

**Comment by Frepke** [comment]
Okay,

I've put an extra line (echo $status) in healthcheck.sh so I could see the result from the ping command.
The healthcheck often has error 1/ as a result so I've changed the -w option from 1 to 2 which solved the problem for me.

In the past, I had a similar problem with a curl-command in a Lua script in a domoticz container.
Then I read somewhere on the internet that ping and curl commands often are much slower from within a Docker container as from the host cli itself. 

kr.,
Frepke
