### ISSUE TITLE
Tinyproxy HTTPS connection

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#29]
I have Tinyproxy up and running, it works really great.
Can you confirm that Tinyproxy is using http between client and Tinyproxy communication, therefore the connection between client and Tinyproxy is not encrypted?
It doesn't really matter in home network environment. But it is not advised to use this from outside of home network as a proxy, if I get this correctly. 
Looking into Tinyproxy I believe it doesn't do https transparent proxy, so I think this can't be done. The only https transparent proxy would be Squid. If configured as https transparent proxy, than basically it acts a man-in-a-middle to encrypt/decrypt traffic going from client and Squid. Do I get this right?

**Comment by qdm12** [comment]
I think you do! You would need an HTTPS proxy (Caddy with the forward proxy does it too). But it gets quite troublesome to do so as you cannot "forward" an HTTP proxy request from a proxy to another apparently.

The way I'm looking at is to have a VPN server (look at wireguard it's great! I'm working on some Docker images at https://github.com/qdm12/wireguard) in my network so that I can tunnel there and then connect to PIA's Tinyproxy... I know that's a lot of tunneling :smile:

**Comment by qdm12** [comment]
In the end I have setup wireguard without Docker (as it runs in the Kernel space so Docker is sort of pointless). I use it to VPN to my server securely and I can then access PIA's tinyproxy without trouble. Let me know if you would want help setting this up!

**Comment by gurabli** [comment]
I was looking at Wireguard some time ago, but didn't manage to configure it and had no time to investigate further. If you have some time, a guide would be really appreciated. Not a problem that it is not in docker, as it is in kernel - the best. I'm running Ubuntu Server. Thanks for your help!

**Comment by qdm12** [comment]
Ok that was rushed on my phone, but here is a guide for you: [Gist guide](https://gist.github.com/qdm12/35ab96d6be470ce7a4314722a55a1859)
