### ISSUE TITLE
Authenticate/Decrypt packet error: bad packet ID

### ISSUE THREAD

**Issue by chazragg** [qdm12/private-internet-access-docker#36]
i have noticed a lot of these errors appearing in the dockers logs 

`Sun Jul 28 22:04:42 2019 Authenticate/Decrypt packet error: bad packet ID (may be a replay): [ #34680465 ] -- see the man page entry for --no-replay and --replay-window for more info or silence this warning with --mute-replay-warnings`

i noticed in ticket number #34 they had a similar issue and you pinned it down to the torrent client ( i am currently using Qbittorrent) but it did not get solved

is it something that could affect performance or am i safe to just ignore these errors ?

**Comment by qdm12** [comment]
Hi,

You are safe to ignore these errors and it should not affect performance, you could use the `command: --mute-replay-warnings` in your *docker-compose.yml* for now to clean off your logs from these warnings.

These are due to torrenting clients packing too much data in a packet and the VPN connection complains about it. [This comment](https://www.reddit.com/r/VPNTorrents/comments/8jksb5/openvpn_authenticatedecrypt_packet_error_whats/dz1i0dj?utm_source=share&utm_medium=web2x) on Reddit explains it better among the other comments.

Feel free to continue the issue discussion in #34 that I re-opened. Thanks!
