### ISSUE TITLE
Release history

### ISSUE THREAD

**Issue by gurabli** [qdm12/private-internet-access-docker#39]
I am using your docker image from almost the beginning, and we did some great brainstorming over the time. You are doing an amazing work here. By far the best container out there with great support!

I would recommend to do a release description with versioning. I know it is more work, but this container would deserve this. 
And, it would be great if you could keep few previous versions available to pull, if a new version brakes something. So we could revert back to a working version by pulling that specific tag, not only the latest. What do you think? 
And again, really great work!

**Comment by qdm12** [comment]
Yes that's a good idea, although it would need to be somewhat automated because:
- PIA image is automatically built every 5 days to contain the latest malicious IPs and hostnames
- I need to setup a Docker image build pipeline on my raspberry pi to build all kind of ARM architecture images.

My guess is to have a release tag with CPU architecture + timestamp, in example `aarch64-1564841015`. A `releases` file could be in the repository containing all tags, their date and release notes. The release tag and release notes could also be in the labels of the Docker image. I can probably mirror the tags between Github releases and Docker tags, I'll look into it.

Anyway, there is probably a lot of CI configuration ahead. Let me know if you have a better idea or comments! And thanks for your comments and help of course.

**Comment by qdm12** [comment]
Not great, but if I mess up the code on the master branch again, you can fallback manually to an older commit using the method described in [this section](https://github.com/qdm12/private-internet-access-docker#troubleshooting). It's not ideal or automated but it works 👍  It may help a few from time to time.

**Comment by qdm12** [comment]
Hello gurabli, just a little update;

I am messing with travis on my [dns over tls docker image travis branch](https://github.com/qdm12/cloudflare-dns-server/commit/0b7ea1154d4018c761582e56f77583be513c2f79) to (hopefully) build images for all architectures so that pulling it would pull the right image directly 👍  But it doesn't work yet 😢 

I will plug in releases and docker tags for PIA as soon as I make it work, but it might well be a few other days. If you know any other way to build images for multiple architectures, feel free to comment! :) Thanks!
