### ISSUE TITLE
/entrypoint.sh: not found

### ISSUE THREAD

**Issue by jeliasson** [qdm12/private-internet-access-docker#74]
Hi,

It looks like the latest commit #71 broke the entrypoint.

```
/bin/sh: /entrypoint.sh: not found
/bin/sh: /entrypoint.sh: not found
/bin/sh: /entrypoint.sh: not found
```

Which tags are considered stable? Running `latest` is not justified anymore.

Thank you.

**Comment by qdm12** [comment]
The entrypoint is `/entrypoint` and was updated in the Docker image. You should not have to manually set the entrypoint.

Otherwise you can use the Docker image tags `old` (amd64 only) or `v1`

**Comment by jeliasson** [comment]
> You should not have to manually set the entrypoint.

I don't. Using `qmcgaw/private-internet-access:latest` with no `entryfile` or `command` defined in the docker-compose file. After removing the container all together and recreate, it seems to be working up again with some env changed needed. I guess it's a caching issue or something.

> Otherwise you can use the Docker image tags `old` (amd64 only) or `v1`

Thanks! I'll stick with this one for now. 

Have you considering having a `stable` tag for versions that have been battle tested, or a `stage` branch/tag that are one or two weeks ahead of `master`?

Anyway,
Keep up the good work! :)

**Comment by qdm12** [comment]
Thanks for the tip, I have considered having branches and such but it's a lot to manage (on top of other github repositories as well!), so I just make a new tag once in a while once it has been stable for everyone for some time.

This Go rewrite has been in 'beta' for a week with the `go` tag, a few people tried it and did not report any issue.

But obviously, a lot of people only use the `latest` tag. So merging the branch in master got me submerged with bug reports 😄  At least now, unlike with Shell scripting, I can add unit tests and perhaps even integration tests to the build pipeline so that it does not break.

Anyway, the latest image is quite stable now it seems.
