### ISSUE TITLE
Connected to PIA but returning original IP?

### ISSUE THREAD

**Issue by LDShadowLord** [qdm12/private-internet-access-docker#9]
Hi, so i've set all this up but my testing is showing that it's not working at all.

- I think I have my "/dev/net/tun" set up (Genuinely not 100% sure, not familiar with it)
- A network has been created "vpnnet"
- The file auth.conf has been created, and is being read properly as the logs show it connecting to PIA.
- Your run command was used, with the only exception being the location of auth.conf changed (On the host side) and the network name changed to "vpnnet", and the location changed to New York.

So the container is declaring itself as unhealthy, and i've also attached a python-alpine container to it and have been running python commands, and that is also returning my original IP.

Is it possible that you could help me find out what is wrong? Thanks. Let me know if you need anything else and i'll hook you up.

Attached is the log from the container. Apologies about the formatting it was copied and pasted from Portainer.
[log.txt](https://github.com/qdm12/private-internet-access-docker/files/2545595/log.txt)

**Comment by qdm12** [comment]
Hi there,

The /dev/net/tun seems created from the log so that's good. All the vpn
creation/connection seems good too!

The network vpnnet is only used to proxy ports so that you can access them
(i. e. a web ui).

Please test with:

docker run --rm --network=container:pia alpine:3.8 wget -qO-
https://ipinfo.io/ip


Does this retun the same IP address as running

wget -qO- https://ipinfo.io/ip


on the host machine?

I'm travelling until tonight so I'll test out the container this evening to
check everything works correctly if you're still having the issue. The
unhealthy problem shouldn't happen though I'll check that anyway.

Thanks!

Quentin

**Comment by qdm12** [comment]
try with

docker run --rm --net=container:pia alpine:3.8 wget -qO-
https://diagnostic.opendns.com/myip

ipinfo.io might be blocked as a malicious hostname perhaps, I'll change
that...

The container can't access standard HTTP(s) using your original IP due to
the firewall (iptables) normally. What host OS are you using?

**Comment by LDShadowLord** [comment]
That command gives the same error, bad address.
I'm running Ubuntu 18.04.1 LTS, it's running as a virtual machine on ESXi.

**Comment by qdm12** [comment]
That's likely to be the container not having internet access for an external reason. I unfortunately can't verify the latest version works until tomorrow, sorry about that (I'm missing my PIA credentials...).

**Comment by qdm12** [comment]
I have tested it with `US New York City` with `auth.conf` in read-only mode as your log shows, on a fresh Linux install with the latest container and it works. It returns two different IP addresses as expected. Your container log seems also correct. So it's likely not related to the container but to your setup. Do you have a host firewall in place? I will close the issue for now.
